### ISSUE TITLE
Impossible to uncheck the checkbox/radio buttons

### ISSUE THREAD

**Issue by francoisschwarzentruber** [fusion809/simplex#3]
Once you clicked on a checkbox/radio buttons it is impossible to uncheck it.
![image](https://github.com/fusion809/simplex/assets/43071857/460b347f-dfb2-41fd-bd92-d22fc42d5099)

**Comment by fusion809** [comment]
Thank you for your feature request. I didn't include this feature because reloading the page allows users to start from scratch with the buttons unchecked. Plus I wasn't sure how one could make them uncheckable. Googling has revealed a way of making it work but the user will have to press Ctrl while clicking the checked radio boxes to uncheck them.
